### ISSUE TITLE
Gigaset Problems

### ISSUE THREAD

**Issue by kaeferfreund** [a1comms/freepbx-ldap#2]
Hi everyone,

I just wanted to point out, that the "new" Gigaset DECT base-stations do not send a query-size when you want to see the details of a specific contact. This results in the querry size being 0 and the sql querry being empty...

Just in case someone is having the same issue.

**Comment by kaeferfreund** [comment]
okay - there where still some more issues due to the way Gigaset implemented their LDAP stuff.

As my changes probably break the snom implementation and I don't have any snom devices for testing on hand, I forked the repo:

https://github.com/kaeferfreund/freepbx-ldap

**Comment by iamacarpet** [comment]
@kaeferfreund thanks for the heads up, you were right, we weren't checking if limit was unspecified in the LDAP query and if it was, it defaulted to a LIMIT of 0, which wasn't really very useful.

I've pushed a change and a built release that include a check to make sure LIMIT is actually set, or fallback to a default value of 99, as chosen by you in your branch.

**Comment by kaeferfreund** [comment]
Thanks again for the awesome work! Really great foundation. Unfortunately I don't have any sagoma handsets, so I cannot merge my changes into your main branch, as I can not check if I break anything. Sorry for that. What I also did was add another LDAP Server that serves the contacts from the contact manager, that's maybe something others could be interested in...
