### ISSUE TITLE
Mysql query does not works

### ISSUE THREAD

**Issue by silvergo** [a1comms/freepbx-ldap#3]
Hello, good work.
I tested it on a raspbx. The ldap server works but the ldap query (with ldapsearch) does not return any result.
I tried to analize with wireshark the query executed by freebpx-ldap to mysql to localhost on localhost. Seems to be an answer without extensions.
Same query executed in mysql commad line client return a complete set.

This is the ldapsearch query:
ldapsearch -h 192.168.12.100:10389 -x -b 'dc=asterisk'

This is the output of freepbx-ldap:
2020/03/26 14:45:19 Listening on :10389
2020/03/26 14:45:21 Connection client [1] from <ldapsearchclient>:<port> accepted
2020/03/26 14:45:21 <<< 1 - BindRequest - hex=&{300c020101600702010304008000}
2020/03/26 14:45:21 >>> 1 - BindResponse - hex=300c02010161070a010004000400
2020/03/26 14:45:21 <<< 1 - SearchRequest - hex=&{3030020102632b040b64633d617374657269736b0a01020a0100020100020100010100870b6f626a656374636c6173733000}
2020/03/26 14:45:21 
2020/03/26 14:45:21  ROUTE MATCH ; Search - Generic
2020/03/26 14:45:21 
2020/03/26 14:45:21 Request BaseDn=dc=asterisk
2020/03/26 14:45:21 Request Filter="objectclass"
2020/03/26 14:45:21 Request FilterString=(objectclass=*)
2020/03/26 14:45:21 Request Attributes=[]
2020/03/26 14:45:21 Request TimeLimit=0
2020/03/26 14:45:21 Request SizeLimit=0
2020/03/26 14:45:21 Searching without filter...
2020/03/26 14:45:21 Query SQL: SELECT name, extension FROM users   ORDER BY name ASC LIMIT 0, ? []interface {}{0}
2020/03/26 14:45:21 >>> 1 - SearchResultDone - hex=300c02010265070a010004000400
2020/03/26 14:45:21 <<< 1 - UnbindRequest - hex=&{30050201034200}
2020/03/26 14:45:21 client 1 close()
2020/03/26 14:45:21 client 1 close() - stop reading from client
2020/03/26 14:45:21 client 1 close() - Abandon signal sent to processors
2020/03/26 14:45:21 client [1] request processors ended
2020/03/26 14:45:21 client [1] connection closed

And this is what I see in wireshark:
    00000000  62 00 00 00 0a 35 2e 35  2e 35 2d 31 30 2e 31 2e   b....5.5 .5-10.1.
    00000010  33 38 2d 4d 61 72 69 61  44 42 2d 30 2b 64 65 62   38-Maria DB-0+deb
    00000020  39 75 31 00 7d 03 00 00  3b 32 28 72 2a 76 37 4d   9u1.}... ;2(r*v7M
    00000030  00 ff f7 2d 02 00 3f a0  15 00 00 00 00 00 00 00   ...-..?. ........
    00000040  00 00 00 5c 68 74 30 30  40 2f 6c 52 38 5e 51 00   ...\ht00 @/lR8^Q.
    00000050  6d 79 73 71 6c 5f 6e 61  74 69 76 65 5f 70 61 73   mysql_na tive_pas
    00000060  73 77 6f 72 64 00                                  sword.
00000000  45 00 00 01 8d a2 0a 00  00 00 00 00 2d 00 00 00   E....... ....-...
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000020  00 00 00 00 72 6f 6f 74  00 00 61 73 74 65 72 69   ....root ..asteri
00000030  73 6b 00 6d 79 73 71 6c  5f 6e 61 74 69 76 65 5f   sk.mysql _native_
00000040  70 61 73 73 77 6f 72 64  00                        password .
    00000066  07 00 00 02 00 00 00 02  00 00 00                  ........ ...
00000049  3e 00 00 00 16 53 45 4c  45 43 54 20 6e 61 6d 65   >....SEL ECT name
00000059  2c 20 65 78 74 65 6e 73  69 6f 6e 20 46 52 4f 4d   , extens ion FROM
00000069  20 75 73 65 72 73 20 20  20 4f 52 44 45 52 20 42    users    ORDER B
00000079  59 20 6e 61 6d 65 20 41  53 43 20 4c 49 4d 49 54   Y name A SC LIMIT
00000089  20 3f                                               ?
    00000071  0c 00 00 01 00 01 00 00  00 02 00 01 00 00 00 00   ........ ........
    00000081  17 00 00 02 03 64 65 66  00 00 00 01 3f 00 0c 3f   .....def ....?..?
    00000091  00 00 00 00 00 fd 80 00  00 00 00 05 00 00 03 fe   ........ ........
    000000A1  00 00 02 00 30 00 00 04  03 64 65 66 08 61 73 74   ....0... .def.ast
    000000B1  65 72 69 73 6b 05 75 73  65 72 73 05 75 73 65 72   erisk.us ers.user
    000000C1  73 04 6e 61 6d 65 04 6e  61 6d 65 0c 2d 00 c8 00   s.name.n ame.-...
    000000D1  00 00 fd 00 00 00 00 00  3a 00 00 05 03 64 65 66   ........ :....def
    000000E1  08 61 73 74 65 72 69 73  6b 05 75 73 65 72 73 05   .asteris k.users.
    000000F1  75 73 65 72 73 09 65 78  74 65 6e 73 69 6f 6e 09   users.ex tension.
    00000101  65 78 74 65 6e 73 69 6f  6e 0c 2d 00 50 00 00 00   extensio n.-.P...
    00000111  fd 09 40 00 00 00 05 00  00 06 fe 00 00 02 00      ..@..... .......
0000008B  16 00 00 00 17 01 00 00  00 00 01 00 00 00 00 01   ........ ........
0000009B  08 00 00 00 00 00 00 00  00 00                     ........ ..
    00000120  01 00 00 01 02 30 00 00  02 03 64 65 66 08 61 73   .....0.. ..def.as
    00000130  74 65 72 69 73 6b 05 75  73 65 72 73 05 75 73 65   terisk.u sers.use
    00000140  72 73 04 6e 61 6d 65 04  6e 61 6d 65 0c 2d 00 c8   rs.name. name.-..
    00000150  00 00 00 fd 00 00 00 00  00 3a 00 00 03 03 64 65   ........ .:....de
    00000160  66 08 61 73 74 65 72 69  73 6b 05 75 73 65 72 73   f.asteri sk.users
    00000170  05 75 73 65 72 73 09 65  78 74 65 6e 73 69 6f 6e   .users.e xtension
    00000180  09 65 78 74 65 6e 73 69  6f 6e 0c 2d 00 50 00 00   .extensi on.-.P..
    00000190  00 fd 09 40 00 00 00 05  00 00 04 fe 00 00 02 00   ...@.... ........
    000001A0  05 00 00 05 fe 00 00 02  00                        ........ .
000000A5  05 00 00 00 19 01 00 00  00                        ........ .

There is no extension namber/name in the answers.

I'm not very confident with go lang. How could I try to debug?

Thank you

**Comment by iamacarpet** [comment]
Hello @silvergo ,

This looks like it is related to #2 , which I've just pushed fixed for.

Can you give it another go and see how you get on please?

Re-open if you have any problems.

Regards,
iamacarpet
